In [1]:
import numpy as np
a = np.zeros(10) + 5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [2]:
import numpy as np
print(np.pi)
print(np.sin(0))
print(np.cos(np.pi))

3.141592653589793
0.0
-1.0


In [3]:
import numpy as np
a = np.random.rand(5)
print(a)
print(type(a))

[0.05129361 0.48752326 0.03881759 0.98827003 0.03891172]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
print(np.random.choice(6, 10))

[4 1 4 3 5 3 4 1 2 4]


In [6]:
import numpy as np
print(np.random.choice(10, 6, replace = False))

[2 0 1 8 4 9]


In [8]:
import csv
f = open('Busan_1206.csv', encoding='utf-8')
data = csv.reader(f)
print(data)
header = next(data)
print(header)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 0: invalid continuation byte